import React from "react";
import { Button } from "../core/Button.jsx";
const P = (d, s = 20) => <svg viewBox="0 0 24 24" width={s} height={s} fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{d.map((x, i) => <path key={i} d={x} />)}</svg>;
const I = { pin: ["M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0", "M15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0"], phone: ["M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384"], clock: ["M12 6v6l4 2", "M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0"], mail: ["m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7", "M4 4h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z"], up: ["m5 12 7-7 7 7", "M12 19V5"] };
export const FOOTER_SERVICES = ["Envíos Express", "Envíos LowCost", "Envíos Flex (MeLi)", "Cuenta Corriente", "Plan Emprendedores", "Depósito y Fulfillment", "Cobro en destino", "Cotizador online"];
/** Footer del sitio: franja amarilla, banda CTA, marca + canales, servicios, base MDQ, legales. */
export function SiteFooter({ services = FOOTER_SERVICES, social, onNavigate, onCta, year = 2026, style }) {
  const link = (t, strong) => <a key={t} href="#" onClick={(e) => { e.preventDefault(); onNavigate && onNavigate({ label: t }); }} style={{ display: "inline-flex", alignItems: "center", minHeight: 44, font: strong ? "400 18px/1 var(--font-subheading)" : "400 14px/1.4 var(--font-sans)", letterSpacing: strong ? ".05em" : 0, textTransform: strong ? "uppercase" : "none", color: strong ? "var(--color-white)" : "rgba(255,255,255,.85)", transition: "color var(--duration-base), transform var(--duration-base)" }} onMouseEnter={(e) => { e.currentTarget.style.color = "var(--color-brand-yellow-500)"; e.currentTarget.style.transform = "translateX(4px)"; }} onMouseLeave={(e) => { e.currentTarget.style.color = strong ? "var(--color-white)" : "rgba(255,255,255,.85)"; e.currentTarget.style.transform = "none"; }}>{t}</a>;
  const base = [["pin", "Dirección", "Friuli 1972 · Mar del Plata"], ["phone", "WhatsApp", "+54 223 660-2699"], ["clock", "Horarios", "Lun a Vie 09:00 - 18:00 · Sáb 10:00 - 15:00"], ["mail", "Email", "matiascejas@enviosdosruedas.com"]];
  return <footer style={{ position: "relative", background: "var(--color-brand-blue-500)", color: "var(--color-white)", borderTop: "1px solid rgba(255,255,255,.1)", fontFamily: "var(--font-sans)", overflow: "hidden", ...style }}>
    <div style={{ height: 6, background: "var(--color-brand-yellow-500)", boxShadow: "var(--shadow-accent-md)" }}></div>
    <div aria-hidden="true" style={{ position: "absolute", inset: 0, opacity: .04, pointerEvents: "none", backgroundImage: "linear-gradient(90deg,#fff 1px,transparent 1px),linear-gradient(#fff 1px,transparent 1px)", backgroundSize: "32px 32px" }}></div>
    <div style={{ position: "relative", maxWidth: "var(--container-page)", margin: "0 auto", padding: "var(--section-y) var(--page-gutter-lg) 24px", display: "flex", flexDirection: "column", gap: 48 }}>
      <div style={{ borderRadius: "var(--radius-card)", background: "rgba(9,80,246,.9)", border: "1px solid rgba(255,255,255,.15)", boxShadow: "var(--shadow-2xl)", padding: 32, display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 24 }}>
        <div style={{ display: "flex", flexDirection: "column", gap: 12, maxWidth: 520 }}>
          <span style={{ alignSelf: "flex-start", display: "inline-flex", alignItems: "center", gap: 8, padding: "4px 12px", borderRadius: 999, border: "1px solid rgba(255,236,1,.3)", background: "rgba(255,236,1,.15)", color: "var(--color-brand-yellow-500)", font: "400 14px/1.2 var(--font-subheading)", letterSpacing: ".05em", textTransform: "uppercase" }}><span style={{ position: "relative", width: 8, height: 8 }}><span style={{ position: "absolute", inset: 0, borderRadius: "50%", background: "var(--color-brand-yellow-500)", animation: "var(--animate-ping)" }}></span><span style={{ position: "absolute", inset: 0, borderRadius: "50%", background: "var(--color-brand-yellow-500)" }}></span></span>Operaciones activas Mar del Plata {year}</span>
          <h3 style={{ margin: 0, font: "400 clamp(1.5rem,3vw,2rem)/1.1 var(--font-display)", letterSpacing: "-.025em", textTransform: "uppercase" }}>¿Tenés envíos para hoy? <span style={{ color: "var(--color-brand-yellow-500)" }}>Los entregamos a tiempo.</span></h3>
          <p style={{ margin: 0, font: "400 14px/1.625 var(--font-sans)", color: "rgba(255,255,255,.85)" }}>Cotizá online en segundos o coordiná directo con nuestro equipo logístico por WhatsApp.</p>
        </div>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 12 }}><Button onClick={onCta}>Cotizá tu envío</Button><Button variant="secondary" surface="dark" external href="https://wa.me/542236602699">Chateá con nosotros</Button></div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(240px,1fr))", gap: 40 }}>
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <span style={{ font: "400 var(--text-3xl)/1 var(--font-display)", textTransform: "uppercase", letterSpacing: "var(--tracking-tight)" }}>Envíos <span style={{ color: "var(--color-brand-yellow-500)" }}>DosRuedas</span></span>
          <p style={{ margin: 0, font: "400 14px/1.625 var(--font-sans)", color: "rgba(255,255,255,.85)", maxWidth: "36ch" }}>Con más de 7 años de trayectoria en Mar del Plata, transformamos el despacho de tus productos en un motor de crecimiento para emprendedores, PyMEs y comercios locales.</p>
          {social && <div><span style={{ display: "block", marginBottom: 8, font: "400 12px/1.3 var(--font-subheading)", letterSpacing: ".1em", textTransform: "uppercase", color: "var(--color-brand-yellow-500)" }}>Canales oficiales</span><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{social}</div></div>}
        </div>
        <div><h4 style={{ margin: "0 0 8px", paddingBottom: 8, borderBottom: "1px solid rgba(255,255,255,.1)", font: "400 18px/1 var(--font-subheading)", letterSpacing: ".05em", textTransform: "uppercase", color: "var(--color-brand-yellow-500)" }}>Servicios y cotizadores</h4><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", columnGap: 16 }}>{services.map((s) => link(s, true))}</div></div>
        <div><h4 style={{ margin: "0 0 12px", paddingBottom: 8, borderBottom: "1px solid rgba(255,255,255,.1)", font: "400 18px/1 var(--font-subheading)", letterSpacing: ".05em", textTransform: "uppercase", color: "var(--color-brand-yellow-500)" }}>Base de operaciones MDQ</h4><div style={{ display: "flex", flexDirection: "column", gap: 8 }}>{base.map(([ic, t, v]) => <div key={t} style={{ display: "flex", gap: 12, alignItems: "center", padding: 10, borderRadius: "var(--radius-control)", background: "rgba(9,80,246,.8)", border: "1px solid rgba(255,255,255,.15)" }}><span style={{ width: 36, height: 36, flexShrink: 0, borderRadius: 12, background: "rgba(255,255,255,.1)", color: "var(--color-brand-yellow-500)", display: "inline-flex", alignItems: "center", justifyContent: "center" }}>{P(I[ic], 18)}</span><span style={{ display: "flex", flexDirection: "column", font: "400 12px/1.4 var(--font-mono)", color: "rgba(255,255,255,.85)", fontVariantNumeric: "tabular-nums" }}><b style={{ fontWeight: 400, fontFamily: "var(--font-subheading)", letterSpacing: ".1em", textTransform: "uppercase", color: "var(--color-white)", fontSize: 14 }}>{t}</b>{v}</span></div>)}</div></div>
      </div>
      <div style={{ borderTop: "1px solid rgba(255,255,255,.1)", paddingTop: 24, display: "flex", flexDirection: "column", gap: 12, alignItems: "flex-start" }}>
        <Button size="sm" icon={P(I.up, 16)} onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} aria-label="Volver arriba">Volver arriba</Button>
        <div style={{ width: "100%", display: "flex", flexWrap: "wrap", justifyContent: "space-between", gap: 8 }}>
          <div style={{ display: "flex", flexWrap: "wrap", columnGap: 20, alignItems: "center", font: "400 12px/1.4 var(--font-sans)", color: "rgba(255,255,255,.85)" }}><span style={{ color: "var(--color-white)" }}>© {year} Envíos DosRuedas · Mar del Plata, Argentina.</span>{["Servicios", "Cobertura", "Guía MercadoLibre Flex", "Sobre Nosotros", "Preguntas Frecuentes", "Nuestras Redes"].map((l) => link(l))}</div>
          <div style={{ display: "flex", flexWrap: "wrap", columnGap: 20 }}>{["Términos y Condiciones", "Política de Privacidad"].map((l) => link(l))}</div>
        </div>
      </div>
    </div>
  </footer>;
}
