function EmprendedoresScreen({ go }) {
  const [n, setN] = React.useState(120);
  const L = 2400, pct = 20, save = Math.round(L * pct / 100) * n;
  return <>
    <Hero yellow aside={<img src={A("heroes/deposito-local.webp")} alt="Depósito local de Envíos DosRuedas en Friuli 1972" style={{ width: "100%", maxWidth: 480, justifySelf: "center", borderRadius: "var(--radius-card)" }} />}>
      <Badge tone="invert" icon={<Icon d={ICONS.store} />}>Plan emprendedores</Badge>
      <H1 color="var(--color-brand-blue-500)">Logística 3PL y paquetería <span style={{ display: "inline-block", background: "var(--color-brand-blue-500)", color: "var(--color-brand-yellow-500)", borderRadius: 999, padding: "0 .3em", transform: "rotate(-1deg)", lineHeight: 1.1 }}>e-commerce</span></H1>
      <Lead>Almacenamos tu stock en Friuli 1972. Cuando vendés, nosotros empaquetamos, etiquetamos y despachamos en el día.</Lead>
      <div style={{ display: "flex", flexWrap: "wrap", gap: 16 }}><Button variant="social" size="lg" onClick={() => go("contacto")}>Armá tu plan</Button><Button variant="secondary" size="lg" href="#dropoff">Ver DropOFF</Button></div>
    </Hero>
    <Section bg="var(--color-neutral-50)"><SectionHead eyebrow="Soluciones paquetería e-commerce" title="Todo en un mismo lugar" /><Grid min={260}>{[["E-Commerce Same Day (Friuli 1972)", "Guardamos tu stock en nuestro depósito central de Friuli 1972. Al vender, tu producto sale inmediatamente empaquetado con picking por código QR.", "store", "Same day"], ["Opción DropOFF (−20% off)", "Acercá tus paquetes directamente a nuestro depósito en Friuli 1972 y obtené un 20% de descuento automático en la tarifa final de envío.", "pkg", "−20%"], ["Contrareembolso sin cargo extra", "Realizamos cobro contra entrega en destino sin ningún tipo de comisión ni recargo adicional por gestión de cobranza.", "check", "$0 comisión"]].map(([t, b, ic, tag]) => <FeatureCard key={t} icon={<Icon d={ICONS[ic]} size={20} />} tag={tag} title={t} body={b} />)}</Grid></Section>
    <Section><SectionHead eyebrow="Partner logístico especializado" title="Potenciamos tu pyme" lead="Más que un simple servicio de envío, nos convertimos en tu depósito estratégico." /><Grid min={220}>{[["Cuentas corrientes", "Esquemas ágiles de facturación mensual consolidada adaptados al flujo de caja de tu negocio (no emitimos Factura A).", "file"], ["Límites claros y seguros", "Flota de motos y utilitarios. Llevamos bultos de hasta 5 kg con control y seguimiento centralizado vía WhatsApp.", "shield"], ["Almacenaje seguro", "Depósitos propios en Friuli 1972, Mar del Plata, equipados con alta seguridad para el resguardo de tu stock.", "store"], ["Asesor dedicado", "Un operador exclusivo para tu firma: resolvé consultas operativas directamente con personas reales en MDQ.", "users"]].map(([t, b, ic]) => <FeatureCard key={t} icon={<Icon d={ICONS[ic]} size={20} />} title={t} body={b} />)}</Grid></Section>
    <Section bg="var(--color-brand-blue-500)"><div id="dropoff" style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(300px,1fr))", gap: 40, alignItems: "center" }}>
      <div style={{ display: "flex", flexDirection: "column", gap: 20, alignItems: "flex-start" }}><Badge tone="accent" size="sm">Modalidad DropOFF</Badge><H2 color="var(--color-white)">Traé tus envíos y ahorrá <Mark>20%</Mark> en cada despacho</H2><Lead invert>Entregás los paquetes en nuestra base y los despachamos con descuento. Calculá cuánto ahorrás por mes.</Lead></div>
      <BezelCard tone="light" hoverLift={false}><div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
        <span style={{ font: "400 14px/1 var(--font-subheading)", letterSpacing: ".1em", textTransform: "uppercase" }}>Envíos por mes</span>
        <QuantityStepper value={n} onChange={setN} label="Cantidad de envíos por mes" />
        <input type="range" min="1" max="1000" value={n} aria-label="Cantidad de envíos por mes" onChange={(e) => setN(+e.target.value)} style={{ width: "100%", accentColor: "var(--color-brand-blue-500)" }} />
        <FilterChips label="Atajos" options={["25", "100", "250", "500"]} value={String(n)} onChange={(v) => setN(+v)} />
        <div aria-live="polite" style={{ borderTop: "1px solid var(--color-brand-blue-100)", paddingTop: 16 }}><span style={{ font: "400 14px/1 var(--font-subheading)", letterSpacing: ".1em", textTransform: "uppercase" }}>Ahorro estimado</span><div style={{ font: "700 40px/1.1 var(--font-mono)", fontVariantNumeric: "tabular-nums" }}>${save.toLocaleString("es-AR")}<span style={{ font: "400 12px var(--font-mono)" }}> / mes</span></div><p style={{ margin: "4px 0 0", font: "400 12px/1.4 var(--font-mono)" }}>Base: ${L.toLocaleString("es-AR")} por envío − {pct}% (cifra de ejemplo del sitio).</p></div>
        <Button fullWidth external href={"https://wa.me/542236602699?text=" + encodeURIComponent("Hola! Manejo aprox. " + n + " envíos por mes y quiero activar DropOFF (" + pct + "% off) en Mar del Plata.")}>Activar DropOFF</Button>
      </div></BezelCard>
    </div></Section>
    <Section><SectionHead eyebrow="Modalidades e-commerce y 3PL 2026" title="Planes paquetería y fulfillment" lead="Elegí la modalidad e-commerce que mejor impulse tu marca." /><Grid min={260} gap={24} style={{ paddingTop: 12 }}><PricingCard tag="DropOFF 20% off" title="Plan Inicial DropOFF" range="Por envío en MDQ" price="$2.400" unit="por envío" features={["Corte de recepción 13:00 hs", "Descuento del 20% aplicado", "Ruteo same-day garantizado", "Contrareembolso $0 comisión"]} ctaLabel="Elegir plan" onCta={() => go("contacto")} /><PricingCard featured tag="Más popular 2026" title="Plan E-Commerce 3PL" range="Stock gratis" price="$3.000" unit="por envío + stock gratis" features={["Almacenamiento de stock sin costo", "Picking por código QR instantáneo", "Reparto same-day en Mar del Plata", "Seguimiento GPS para tus clientes"]} ctaLabel="Elegir plan" onCta={() => go("contacto")} /><PricingCard tag="Cuenta corriente" title="Plan PyME Corporativo" range="Volumen > 10 envíos/día" price="A medida" unit="" features={["Retiro programado en tu local", "Pagos agrupados semanales, quincenales o mensuales", "Atención prioritaria por WhatsApp", "Tarifa corporativa escalonada"]} ctaLabel="Elegir plan" onCta={() => go("empresas")} /></Grid></Section>
    <CtaForm /><SocialBand />
  </>;
}
window.EmprendedoresScreen = EmprendedoresScreen;
