const SERV = {
  express: { icon: "zap", badge: "Envíos Express", h1: ["Rápido cuando", "importa llegar"], lead: "Entregas prioritarias en el día con elección de franja horaria de 3 horas, pedido con 2 hs de anticipación mínima.", img: "heroes/express-moto.webp", alt: "Moto de Envíos DosRuedas en reparto express", yellow: false,
    stats: [["3 hs", "franja a elección"], ["2 hs", "anticipación mínima"], ["5 kg", "por bulto"]],
    featuresTitle: "Rápido cuando importa llegar", features: [["Entrega en franja horaria de 3 hs a elección", "Pedís, retiramos y vamos directo al destino, con 2 hs de anticipación mínima.", "clock"], ["Bultos de hasta 5 kg", "Sobres, cajas, repuestos, pedidos de tu tienda, hasta 40 x 40 x 40 cm por bulto.", "pkg"], ["Tarifa fija por distancia", "El precio sale de la distancia real entre retiro y entrega.", "pin"], ["Flota propia, sin tercerizar", "Más de 7 años recorriendo Mar del Plata con nuestras propias motos y cadetes.", "shield"]],
    pricingTitle: "Pagás por distancia, no por apuro", pricingTag: "Tarifario transparente 2026 · Mar del Plata", unit: "ARS", cta: (z) => "Cotizar zona " + z,
    prices: [["Zona 1 · Microcentro", "Hasta 3 km", "$3.700", ["Ventana a elegir: franja de 3 hs", "Mandados rápidos dentro del barrio"]], ["Zona 2 · Interbarrial", "Hasta 5 km", "$4.600", ["Ventana a elegir: franja de 3 hs", "Cruces cortos entre zonas"]], ["Zona 3 · Trayecto medio", "Hasta 7 km", "$6.100", ["Ventana a elegir: franja de 3 hs", "De una punta a la otra de la ciudad"], "Tarifa intermedia"], ["Zona 4 · Perímetro urbano", "Hasta 10 km", "$8.200", ["Ventana a elegir: franja de 3 hs", "Recorridos extensos dentro del ejido"]]],
    useTitle: "¿Cuándo te conviene Express?", uses: [["Documentos y trámites", "Contratos, escrituras y papeles que tienen que llegar firmados hoy, entregados en mano.", ["Escribanías y estudios", "Contratos comerciales firmados", "Certificados y habilitaciones"]], ["Insumos y repuestos", "Lo que frena tu trabajo si no llega: repuestos, insumos de local, tecnología.", ["Repuestos para talleres", "Insumos para locales y gastronomía", "Equipos y accesorios"]], ["Entregas con horario", "Cuando el paquete tiene que estar a una hora: un regalo, un evento, una obra.", ["Regalos y sorpresas del día", "Pedidos para eventos y catering", "Obras y oficinas"]]] },
  lowcost: { icon: "trend", badge: "Envíos LowCost", h1: ["Envíos LowCost:", "máxima eficiencia"], lead: "Paquetería y cadetería con entrega el mismo día. Pedís antes de las 13:00 hs y se entrega antes de las 19:00 hs, sin franja horaria fija.", img: "heroes/deposito-local.webp", alt: "Depósito local de Envíos DosRuedas", yellow: true,
    stats: [["13:00", "corte de carga"], ["19:00", "entrega antes de"], ["Fija", "tarifa por distancia"]],
    featuresTitle: "Beneficios LowCost", features: [["Valores LowCost con condiciones de Express", "Disfrutá del mejor precio con un servicio rápido y seguro que se adapta a vos.", "zap"], ["Horario de corte extendido hasta 13 hs", "Ingresá tus envíos del día hasta las 13:00 hs y los entregamos en la misma jornada antes de las 19:00 hs.", "clock"], ["Ruteo urbano eficiente", "Ruteo continuo optimizado que permite la máxima velocidad de entrega en Mar del Plata.", "truck"], ["Ahorro de costos logísticos", "Maximizá tu rentabilidad pagando tarifas súper económicas por cada entrega.", "trend"]],
    pricingTitle: "Tarifas 2026 Envíos LowCost", pricingTag: "Tarifario inteligente 2026", unit: "/ despacho final", cta: (z) => "Ver zona " + z,
    prices: [["Zona 1", "Hasta 3 km", "$3.000", ["Corte de carga 13:00 hs", "Entrega antes de 19:00 hs"], null, "La mejor tarifa para ruteo diario de cercanía."], ["Zona 2", "3 a 5 km", "$4.000", ["Corte de carga 13:00 hs", "Entrega antes de 19:00 hs"], "Recomendado PyME", "Cobertura intermedia económica para PyMEs."], ["Zona 3", "5 a 7 km", "$5.300", ["Corte de carga 13:00 hs", "Entrega antes de 19:00 hs"], null, "Llegamos a distancias medias al mejor costo."], ["Zona 4", "7 a 10 km", "$7.000", ["Corte de carga 13:00 hs", "Entrega antes de 19:00 hs"], null, "Máximo ahorro en distancias urbanas."]],
    stepsTitle: "¿Cómo funciona?", steps: [["Solicitud", "Nos solicitás el envío por WhatsApp."], ["Retiro", "Retiramos el paquete por tu local o depósito en el transcurso del día."], ["Entrega", "Entregamos de forma segura en manos de tu destinatario."]] },
  flex: { icon: "clock", badge: "Mercado Envíos Flex", h1: ["Dominá tus ventas", "con envíos Flex"], lead: "Entregá en el mismo día con Mercado Envíos Flex en Mar del Plata urbana. Horario de corte 15:00 hs y múltiples retiros para cuidar tu reputación.", img: "heroes/inicio-mapa.webp", alt: "Mapa de Mar del Plata con pin de Envíos DosRuedas", yellow: false,
    stats: [["15:00", "horario de corte"], ["1+", "desde 1 paquete"], ["100%", "cumplimiento en el día"]],
    featuresTitle: "Beneficios para vendedores", features: [["Corte 15:00 hs", "Despachá tus ventas hasta las 15:00 hs para entrega garantizada en el mismo día.", "clock"], ["Reputación intacta", "Cumplimos los tiempos pactados para que mantengas tu estatus de MercadoLíder sin sobresaltos.", "shield"], ["Devoluciones sin cargo", "Si el comprador rechaza el producto en el domicilio por cualquier causa, la devolución a tu local es totalmente sin cargo.", "pkg"], ["Todo Mar del Plata", "Cubrimos todas las zonas de entrega habilitadas por MercadoLibre Flex en la ciudad.", "pin"], ["Choferes calificados", "Personal altamente capacitado para brindar la mejor experiencia de entrega.", "users"]],
    pricingTitle: "Niveles y tarifas Flex", pricingTag: "Niveles Flex 2026", unit: "/ liquidación quincenal", cta: () => "Activar nivel",
    prices: [["Nivel 1 · Crecimiento", "1 a 4 envíos diarios", "$3.000", ["Tarifas estándar por distancia en km", "Z5 (+10 km): $7.000 + $700 por km adicional"]], ["Nivel 2 · Pro", "5 a 10 envíos diarios", "$3.000", ["Tope fijo de $6.500 en Z4 y Z5", "Segunda visita Z1 gratis, otras al 50%", "Retiro bonificado sin cargo"], "Recomendado"], ["Nivel 3 · Elite", "+10 envíos diarios", "$4.500", ["Tarifa plana unificada a toda la ciudad"]]],
    stepsTitle: "Logística sin fricciones", steps: [["Vendés", "Recibís una venta con Mercado Envíos Flex en tu panel tradicional de vendedor de MercadoLibre."], ["Retiramos", "Coordinamos y pasamos a retirar todos los paquetes por tu local o depósito en el horario de corte acordado."], ["Entregamos", "Todas las ventas realizadas antes de 15 hs serán entregadas en el día en Mar del Plata."], ["Calificás", "Tu cliente recibe el paquete el mismo día y tu reputación de MercadoLíder sube automáticamente."]],
    useTitle: "¿Qué necesitás?", uses: [["Mercadolibre", "Cuenta activa de vendedor dentro de MercadoLibre.", ["Cuenta de vendedor"]], ["Configuración", "Habilitar la opción de envíos rápidos en el día en tu configuración logística.", ["Envíos Flex activados"]], ["Despacho", "Tener tus paquetes embalados de forma adecuada para el traslado seguro en moto.", ["Embalaje apto para moto"]]] },
};
function ServicioScreen({ go, service = "express" }) {
  const s = SERV[service] || SERV.express;
  const yel = s.yellow; const ink = "var(--color-brand-blue-500)";
  return <>
    <Hero yellow={yel} aside={<img src={A(s.img)} alt={s.alt} style={{ width: "100%", maxWidth: 480, justifySelf: "center", borderRadius: "var(--radius-card)" }} />}>
      <Badge tone={yel ? "invert" : "accent"} icon={<Icon d={ICONS[s.icon]} />}>{s.badge}</Badge>
      <H1 color={yel ? ink : "var(--color-white)"}>{s.h1[0]} <span style={{ display: "inline-block", background: yel ? ink : "var(--color-brand-yellow-500)", color: yel ? "var(--color-brand-yellow-500)" : ink, borderRadius: 999, padding: "0 .3em", transform: "rotate(-1deg)", lineHeight: 1.1 }}>{s.h1[1]}</span></H1>
      <Lead invert={!yel}>{s.lead}</Lead>
      <div style={{ display: "flex", flexWrap: "wrap", gap: 16 }}><Button variant={yel ? "social" : "primary"} size="lg" onClick={() => go("contacto")}>Cotizá {s.badge.replace("Envíos ", "").replace("Mercado ", "")}</Button><Button variant="secondary" surface={yel ? "light" : "dark"} size="lg" onClick={() => go("home")}>Todos los servicios</Button></div>
      <StatList invert={!yel} items={s.stats} />
    </Hero>
    <Section bg="var(--color-neutral-50)">
      <SectionHead eyebrow="Por qué elegirnos" title={s.featuresTitle} />
      <Grid min={240}>{s.features.map(([t, b, ic]) => <FeatureCard key={t} icon={<Icon d={ICONS[ic]} size={20} />} title={t} body={b} />)}</Grid>
    </Section>
    <Section>
      <SectionHead eyebrow={s.pricingTag} title={s.pricingTitle} lead="Tarifa fija según los kilómetros exactos entre retiro y entrega. Sabés el precio antes de pedir." />
      <Grid min={s.prices.length > 3 ? 220 : 260} gap={24} style={{ paddingTop: 12 }}>{s.prices.map((p, k) => <PricingCard key={p[0]} title={p[0]} range={p[1]} price={p[2]} unit={s.unit} features={p[3]} tag={p[4]} note={p[5]} featured={!!p[4]} ctaLabel={s.cta(k + 1)} onCta={() => go("contacto")} />)}</Grid>
    </Section>
    {s.steps && <Section bg="var(--color-neutral-50)"><SectionHead eyebrow="Paso a paso" title={s.stepsTitle} /><Steps items={s.steps.map(([title, body]) => ({ title, body }))} /></Section>}
    {s.uses && <Section bg={s.steps ? "var(--color-white)" : "var(--color-neutral-50)"}>
      <SectionHead eyebrow={s.steps ? "Puesta en marcha" : "Casos de uso"} title={s.useTitle} />
      <Grid min={260}>{s.uses.map(([t, b, li]) => <BezelCard key={t}><div style={{ display: "flex", flexDirection: "column", gap: 12 }}><h3 style={{ margin: 0, font: "400 22px/1.05 var(--font-subheading)", letterSpacing: ".025em", textTransform: "uppercase" }}>{t}</h3><p style={{ margin: 0, font: "400 14px/1.625 var(--font-sans)" }}>{b}</p><ul style={{ listStyle: "none", margin: 0, padding: "12px 0 0", borderTop: "1px solid var(--color-brand-blue-100)", display: "flex", flexDirection: "column", gap: 6 }}>{li.map((x) => <li key={x} style={{ display: "flex", gap: 8, font: "400 14px/1.4 var(--font-sans)" }}><Icon d={ICONS.check} size={16} style={{ flexShrink: 0, marginTop: 2 }} />{x}</li>)}</ul></div></BezelCard>)}</Grid>
    </Section>}
    <CtaForm />
    <SocialBand />
  </>;
}
window.ServicioScreen = ServicioScreen;
